### R MARKDOWN FORMATS ###

# This chapter gives a brief overview of some of the many other types of output you can produce with R Markdown.
# There are two ways to set the output of a document:

# 1. Permanently, by modifying the YAML header:

  ## title: "Viridis Demo"
  ## output: html_document

# 2. Transiently, by calling rmarkdown::render() by hand:

  ## rmarkdown::render(
  ##  "diamond-size.Rmd",
  ##  output_format = "word_document")
  
  ## This is useful if you want to programmatically produce multiple types of output.


# OUTPUT OPTIONS

  ## Each output format is associated with an R function.
  ## You can either write 'foo' or 'pkg::foo'. 
  ## If you omit 'pkg', the default is assumed to be 'rmarkdown'.
  ## It's important to know the name of the function that makes the output because that's where you get help.
  ## For example, to figure out what parameters you can set with html_document, look at:

?rmarkdown::html_document()

# DOCUMENTS:

  ## The previous chapter focused on the default html_document output.
  ## There are number of basic variations on that theme, generating different types of documents:

    ### 'pdf_document' makes a PDF with LaTeX
    ### 'word_document' for Microsoft Word (.docx)
    ### 'odt_document' for OpenDocument Text (.odt)
    ### 'rdf_document' for Rich Text Format (.rtf)
    ### 'md_document' for a Markdown document.
    ### 'github_document', that is a tailored version of md_document designed for sharing on GitHub.

  ## Remember, when generating a document to share with decision makers, you can turn off the default display of code
  ## by setting global options in the setup chunk:

    ### knitr::opts_chunk$set(echo = FALSE)

  ## For html_documents another option is to make the code chunks hidden by default, but visible with a click:

    ### output:
    ###   html_document:
    ###     code_folding: hide


# NOTEBOOKS

  ## A notebook, 'html_notebook', is a variation on an 'html_document'.
  ## The rendered outputs are very similar, but the purpose is different.
  ## An html_document is focused on communicating with decision makers, 
  ## while a notebook is focused on collaborating with other data scientists.
  ## These different purposes lead to using the HTML output in different ways.
  ## Both HTML outputs will contain the fully rendered output, but the notebook also contains the full source code.
  ## That means you can use the .nb.html generated by the notebook in two ways:

    ### You can view it in a web browser, and see the rendered output.
      #### Unlike html_document, this rendering always includes an embedded copy of the source code that generated it.

    ### You can edit it in RStudio. When you open an .nb.html file, RStudio will automatically re-create the .Rmd file
      #### that generated it. In the furute, you can also include supporting files (e.g., data files), 
      #### which will be automatically extracted when needed.

  ## Emailing .nb.html files is a simple way to share analyses with your colleagues. 
  ## But things will get painful as soon as they want to make changes.
  ## If this starts to happen, it's a good time to learn Git and GitHub.
  ## Learning Git and GitHub is definitely painful at first, but the collaboration payoff is huge.
  ## There's one tip that's useful if you're already using them: 
    ### use both 'html_notebook' and 'github_document' outputs:

      #### output:
      ####  html_notebook: default
      ####  github_document: default

  ## 'html_notebook' gives you a local preview, and a file that you can share via email.
  ## 'github_document' creates a minimal MD file that you can check into Git.
  ## You can easily see how the results of your analysis (not just the code) change over time, and GitHub will
    ### render it for you nicely online.



# PRESENTATIONS

  ## You can also use R Markdown to produce presentations.
  ## You get less visual control than with a tool like Keynote or PowerPoint, but automatically inserting the results
  ## of your code into a presentation can save a huge amount of time.
  ## Presentations work by dividing your content into slides, with a new slide beginning at each first (#) or
  ## second (##) level header. You can insert a horizontal rule (***) to create a new slide without a header.

  ## R Markdown comes with three presentations formats built in:

    ### 'ioslides_presentation'
      #### HTML presentation with ioslides

    ### 'slidy_presentation'
      #### HTML presentation with W3C Slidy

    ### 'beamer_presentation'
      #### PDF presentation with LaTeX Beamer

  ## Two other popular formats are provided by packages:

    ### revealjs::revealjs_presentation
      #### HTML presentation with reveal.js. Requires the 'revealjs' package.

    ### 'rmdshower'
      #### https://github.com/MangoTheCat/rmdshower
      #### Provides a wrapper around the shower (https://github.com/shower/shower) presentation engine.



# DASHBOARDS

  ## Dashboards are a useful way to communicate large amounts of information visually and quickly.
  ## 'flexdashboard' makes it particularly easy to create dashboards using R Markdown and a convention for 
  ## how the headers affect the layout:

  ## Each level 1 header (#) begins a new page in the dashboard.
  ## Each level 2 header (##) begins a new column.
  ## Each level 3 header (###) begins a new row.

  ## See the example on page 473 

  ## 'flexdashboard' also provides simple tools for creating sidebars, tabsets, value boxes, and gauges.
  ## To learn more about 'flexdashboard' visit http://rmarkdown.rstudio.com/flexdashboard



# INTERACTIVITY

  ## Any HTML format (document, notebook, presentation, or dashboard) can contain interactive components.
  
# HTMLWIDGETS

  ## HTML is an interactive format, and you can take advantage of that interactivity with htmlwidgets, R functions
  ## that produce interactive HTML visualizations.
  ## The great thing about htmlwidgets is that you don't need to know anything about HTML or JavaScript to use them.
  ## All the details are wrapped inside the package, so you don't need to worry about it.

  ## There are many packages that provide htmlwidgets, including:

    ### 'dygraphs' for interactive time series visualizations
      #### http://rstudio.github.io/dygraphs

    ### 'DT' for interactive tables.
      #### http://rstudio.github.io/DT
    
    ### 'rthreejs' for interactive 3D plots.
      #### https://github.com/bwlewis/rthreejs

    ### 'DiagrammeR' for diagrams (like flow charts and simple node-link diagrams)
      #### http://rich-iannone.github.io/DiagrammeR

  ## To learn more about htmlwidgets and see a more complete list of packages that provide them,
  ## visit http://www.htmlwidgets.org


# SHINY

  ## htmlwidgets provide client-side interactivity - all the interactivity happens in the browser, independently of R
  ## On one had, that's great because you can distribute the HTML file without any connection to R.
  ## However, that fundamentally limits what you can do to things that have been implemented in HTML and JavaScript.
  
  ## An alternative approach is to use Shiny, 
    ### a package that allows you to create interactivity using R code, not JavaScript.

  ## To call Shiny code from an R Markdown document, add 'runtime:shiny' to the header.

    ### title: "Shiny Web App"
    ### output: html_document
    ### runtime: shiny

  ## Then you can use the "input" functions to add interactive components to the document:

library(shiny)

textInput("name", "What is your name?")
numericInput("age", "How old are you?", NA, min = 0, max = 150)

  ## You can then refer to the values with input$name and input$age,
  ## and the code that uses them will be automatically rerun whenever they change.

  ## Shiny apps need a Shiny server to be run online.
  ## When you run Shiny apps on your own computer, Shiny automatically sets up a Shiny server for you,
  ## but you need a public-facing Shiny server if you want to publish this sort of interactivity online.

  ## That's the fundamental trade-off of Shiny: you can do anything in a Shiny document that you can do in R, 
  ## but it requires someone to be running R.

  ## Learn more about Shiny at http://shiny.rstudio.com


# WEBSITES

  ## With a little additional infrastructure you can use R Markdown to generate a complete website:

  ## Put your .Rmd files in a single directory. index.Rmd will become the home page.
  ## Add a YAML file named _site.yml that provides the navigation for the site.
  ## See example on page 477.

  ## Execute rmarkdown::render_site() to build _site, a directory of files ready to deploy as a standalone static website.
  
  ## Read more at http://bit.ly/RMarkdownWebsites


# OTHER FORMATS

  ## Other packages provide even more output formats:

  ## The 'bookdown' (https://github.com/rstudio/bookdown) package makes it easy to write books, like this one.
    ### To learn more, read 'Authoring Books with R Markdown' (https://bookdown.org/yihui/bookdown)
    ### Visit http://www.bookdown.org to see other bookdown books written by the wider R community.

  ## The 'preetydoc' (https://github.com/yixuan/prettydoc) package provides lightweight document formats with 
    ### a range of attractive themes.

  ## The 'rticles' (https://github.com/rstudio/rticles) package compiles a selection of formats tailored for 
    ### specific scientific journals.

  ## See htttp://rmarkdown.rstudio.com/formats.html for a list of even more formats.
  ## You can also create your own by following the instructions at http://bit.ly/CreatingNewFormats


# LEARNING MORE

  ## To learn more about effective communication in these differente formats I recommend the following resources:

  ## To improve your presentation skills, I recommend 'Presentation Patterns' by Neal Ford, M McCollough, and N Schutta.
    ### It provides a set of effective patterns that you can apply to improve your presentations.

  ## If you give academic talks, I recommend reading the 'Leek group guide to giving talks'
    ### https://github.com/jtleek/talkguide

  ## If you're creating a lot of dashboards, make sure to read Stephen Few's:
    ### 'Information Dashboard Design: The Effective Visual Communication of Data'.
    ### It will help you create dashboards that are truly useful, not just pretty to look at.

  ## Effectively communicating your ideas often benefits from some knowledge of graphic design:
    ### 'The Non-Designer's Design Book' is a great place to start.